# syntax=docker/dockerfile:1
FROM alpine:3.20.3
RUN apk -U upgrade && apk update && apk add bash curl openjdk17 ruby-dev ruby-bundler ruby-jekyll npm git msttcorefonts-installer fontconfig && update-ms-fonts
RUN cp `find /usr/lib/ruby/gems/*/gems/jekyll-*/exe/jekyll` /usr/bin
RUN npm install -g fsh-sushi

WORKDIR /trusted-intermediary

CMD ./_updatePublisher.sh -y && ./_genonce.sh
