#!/bin/sh

env=local
path=$CDCTI_HOME/examples/Test/
client_id=flexion
client_sender=simulated-lab
verbose=0

show_help() {
    echo "Usage: $(basename $0) [-e arg] [-c arg] [-s arg]"
    echo
    echo "    -e [local staging]  The environment to run the test in (Default: $env)"
    echo "    -c <arg>  The client id to use"
    echo "    -s <arg>  The client sender to use"
    echo "    -v        Verbose mode"
    echo "    -h        Display this help and exit"
}

while getopts ':e:c:s:vh' opt; do
    case "$opt" in
    e)
        env="$OPTARG"
        ;;
    c)
        client_id="$OPTARG"
        ;;
    s)
        client_sender="$OPTARG"
        ;;
    p)
        client_sender="$OPTARG"
        ;;
    v)
        verbose=1
        ;;
    h)
        show_help
        exit 0
        ;;
    :)
        echo -e "Option requires an argument"
        show_help
        exit 1
        ;;
    ?)
        echo -e "Invalid command option"
        show_help
        exit 1
        ;;
    esac
done
shift "$(($OPTIND - 1))"

# Shift command will shift the positional parameters to the left, discarding the first argument
shift

if [ "$env" = "local" ]; then
    host=localhost
    url=http://$host:7071
    if [ "$client_id" = "flexion" ]; then
        secret="$CDCTI_HOME/mock_credentials/organization-trusted-intermediary-private-key-local.pem"
    fi
elif [ "$env" = "staging" ]; then
    host=staging.prime.cdc.gov
    url=https://$host:443
    # uncomment lines below after setting the path to the staging private key
    # if [ "$client_id" = "flexion" ]; then
    #     secret="$CDCTI_HOME/path/to/flexion/staging/private/key"
    # fi
else
    echo "Usage: $0 <local|staging> <command>"
    exit 1
fi

# if $secret is not set, exit and prompt the user to provide the private key
if [ -z "$secret" ]; then
    echo "Please provide the private key for $client_id"
    exit 1
fi

hurl \
    --variable url=$url \
    --variable client-id=$client_id \
    --variable client-sender=$client_sender \
    --variable jwt=$(jwt encode --exp='+5min' --jti $(uuidgen) --alg RS256 -k $client_id.$client_sender -i $client_id.$client_sender -s $client_id.$client_sender -a $host --no-iat -S @$secret) \
    --file-root $CDCTI_HOME/examples/Test/ \
    --include \
    $@
