name: Automated Staging Test - Run integration tests

on:
  schedule:
    - cron: "0 7 * * 2-6"  # Tuesday to Saturday at 2am EST (7am UTC) - two hours after `automated-staging-test-submit` runs
  workflow_dispatch:

jobs:
  call-staging-test-run:
    uses: ./.github/workflows/staging-test-run_reusable.yml
    with:
      NAME: 'Automated'
      TEST_TYPE: 'test defined assertions on relevant messages'
    secrets: inherit # pragma: allowlist secret
